### PR TITLE
Missing hammerjs ref in typescript

### PR DESCRIPTION
**Pull request by iamlothian**
[Plunker](https://plnkr.co/edit/qVkVM4?p=preview) showing broken example.

Side note: providing a plunker template for recreating issues would be useful.

### CODE REVIEW

**Comment by sheikalthaf** [comment]
Hammerjs will be imported by end-user. If I import it into my carousel. Will it be duplicated?
angular material doing the same

**Comment by iamlothian** [comment]
Hmm, can you share the angualr material link? As far as i am aware and according to the examples and my own implementation. Including hammer js in my code does nothing. A dependancy module

**Comment by iamlothian** [comment]
Interestingly after reading [this](https://stackoverflow.com/questions/41322566/angular-2-could-not-find-hammerjs) i mannaged to fix the plunker by using `import 'hammerjs/hammer';` rather than just `import 'hammerjs'` could have to do with the way the imports are set up? Happy to not merge if you are concerned. 

FYI hammer js would likely not be duplicated by NPM unless seporate versions are required.

**Comment by sheikalthaf** [comment]
https://www.npmjs.com/package/@types/hammerjs check package

**Comment by sheikalthaf** [comment]
This npm package is used to handle hammer typings.

**Comment by sheikalthaf** [comment]
I'm going to merge this PR.
I want some suggestion from you brother.
I think it is better to use `ng-packgr` for bundling this carousel or use the current one we are using.
I tried the ng-packgr but it copying all the dependencies to dist with package file. I don't know how to configure it

**Comment by iamlothian** [comment]
Sorry, im not familiar with `ng-packgr` but it look like the right tool to be using. 

Typing are good, but not the issue here, they only provide typescript info about the module you want to use and are not compiled into your code. 

The code was actually compaining about not having an implementation for `Hammer`. The question here is should hammerjs be a dependency of this package or not. Because you are using it directly in your component id say yes. If it was just an optional polyfill maybe not.

By including this as a dependency, it will be installed when someone installs your package, NPM will install duplicate versions of dependencies if nessasary, as thats just its policy. They can be deduped easily enough. But it won't be bundled into your code, just as angular is not.

**Pull request merged**
